version: '3'

services:
  db: 
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=minishop
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password # this should live in a env var
      - MYSQL_ALLOW_EMPTY_PASSWORD=1 # equivalent to True
    volumes:
      - "./db:/docker-entrypoint-initdb.d" # this is how we persist a sql db even when container stops
    ports:
      - 3308:3306
    networks:
      - mynet

  www:
    build: .
    volumes:
      - "./:/var/www/html" # sync the current dir on local machine to the dir of container
    ports:
      - 8080:80
      - 443:443 # for future ssl traffic
    depends_on:
      - db # Add this line to make sure www container starts after db container
    links:
      - db # Add this line to link www container with db container
    networks:
      - mynet

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
    networks:
      - mynet
    depends_on:
      - db

networks:
  mynet:
    driver: bridge

